### ISSUE TITLE
Problema en el registro de usario

### ISSUE THREAD

**Issue by ArborioEsteban** [ArborioEsteban/ProyectoFinal16i-CodeBeer#17]
[](url)
![image](https://user-images.githubusercontent.com/14060366/220253303-59560fef-f981-44de-8e15-a2ade43ba14e.png)

Consola deja un proble de que 2 campos tienen el mismo identificador(nombre) en archivo FormSignin @RuViz

**Comment by RuViz** [comment]
ya se corrigio lo indicado
