### ISSUE TITLE
Superposicion de navbar

### ISSUE THREAD

**Issue by Nidev-lab** [ArborioEsteban/ProyectoFinal16i-CodeBeer#57]
## Proceso

1. ingrese a la pagina.
2. Me loguee con un usuario.

## Resultado esperado

Que al ingresar todo este correcto.

## Resultado actual

El nav se superpone al texto "Bienvenidos a
 Code & Beer" y al mensaje de bienvenido cuando me logueo.

## Captura

![image](https://user-images.githubusercontent.com/53904695/225099939-e4b2c1fd-eee9-4a02-b19f-da37e5dac1fc.png)

![image](https://user-images.githubusercontent.com/53904695/225101093-72fde44c-0df5-4e20-9dc3-c99a20469bcb.png)

**Comment by ArborioEsteban** [comment]
Hola nicolas , cierto , ya estuve revisando la pagina y el código y es cierto a ciertas alturas pequeñas de dispositivos pasaba eso . Logre encontrar ya la solución.
Hago directamente un merge a master para poder ver los cambios ya en el site?

**Comment by Nidev-lab** [comment]
Hola buenas! Si hacelo en master asi se apliquen los cambios

**Comment by ArborioEsteban** [comment]
Perfecto , ahi subi la correccion a la superposicion del navbar
